name: virus
channels: 
  - defaults
  - conda-forge
  - anaconda
  # - pypi
  
dependencies:
  - python=3.7.0
  - pip=19.3.1
  - pandas=0.25.2
  - numpy=1.17.3
  - requests=2.22.0
  - responses=0.10.6
  - ratelimiter=1.2.0
  - jupyter=1.0.0
  - matplotlib=3.1.1
  - folium=0.10.1
  - joblib=0.14.0
  - geopandas=0.6.0
  - watchdog=0.9.0
  # - altair=4.0.0
  - altair==4.1.0
  - pip:
      # - streamlit==0.52.2
      - streamlit==0.56.0

  